version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    volumes:
      - ./Data:/bot/Data
      - ./books_inf.sql:/bot/books_inf.sql
    environment:
      - TZ=Europe/Belgrade
    restart: unless-stopped
