version: "3.9"

services:
  bot:
    build: .
    container_name: telegram-raise-up-bot
    restart: always
    environment:
      - TZ=Europe/Moscow
      - LOGIN=Egor_Litvin
      - PASSWORD=6234m1234M

    volumes:
      - ./Data:/app/Data
    stdin_open: true
    tty: true
