version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      TOKEN: "${TOKEN}"
      LOGIN: "${LOGIN}"
      PASSWORD: "${PASSWORD}"
    volumes:
      - .:/app
    shm_size: "1gb"
