version: "3.9"
services:
  raise_up_bot:
    image: selenium/standalone-chrome:latest
    volumes:
      - ./Data:/app/Data
      - ./scripts:/app/scripts
      - ./.env:/app/.env:ro
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    command: >
      sh -c "python /app/scripts/raise_up.py"
