version: "3.9"

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    volumes:
      - ./Data:/app/Data
      - ./.env:/app/.env
    environment:
      - TOKEN=${TOKEN}
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    network_mode: "bridge"
