version: '3.9'

services:
  raise_up_bot:
    build: .
    container_name: raise_up_bot
    volumes:
      - ./Data:/app/Data
      - ./scripts:/app/scripts
      - ./.env:/app/.env:ro
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    stdin_open: true
    tty: true
